### ISSUE TITLE
Error 400 (Bad Request)

### ISSUE THREAD

**Issue by lucamp** [TheDavidDelta/lingva-translate#100] opened 2022-03-11 14:34 UTC
Hi,
I am translating a long text from French (or autodetect) to English. It is all the context of [this](https://medias24.com/2022/03/10/experts-la-situation-actuelle-permet-de-supprimer-les-tests-pcr-aux-frontieres/) journal article 

FROM: "Depuis quelques semaines" [...]
TO: [...] dans les endroits clos

and I got this error:

`<style nonce="9FtF/KWg6rHngkrfpfMZEA">`
`      body{overflow:auto!important;display:block!important;}`
`      body>*{display:none!important;}`
`      #af-error-page{display:block!important;}`
`      </style>Error 400 (Bad Request)!!1400. That’s an error.The server cannot process the request because it is malformed. It should not be retried. That’s all we know.`

#workaround
Separate the article in two translation and it works fine, eg

from the beginning till [...] même après un retour à la vie normale [...] and the another translation till the end,

**Comment by TheDavidDelta** [comment] 2022-05-04 17:15
Hello and thanks for the bug report!
And sorry for being this late on the response.

I'm sorry but I'm not able to reproduce your error. This is what happens when I try to translate that same article:
![imagen](https://user-images.githubusercontent.com/6679900/166742265-1489ca63-d2a4-47d5-8b22-4466258423da.png)

Just an standard request error because the text is so big for the GTranslate request and scraping to happen.

Maybe there was some problem with the error parsing on my hosting provider that was fixed in the meantime, as I took so much time to reply. Please try it again and tell me. You can also try in other instances to see if they also have that error.

Regards, David.

**Comment by lucamp** [comment] 2022-05-04 17:56
Just tried and the first error happen when the language is set to autodetect, meanwhile the red warning happens when French is selected

> Just an standard request error because the text is so big for the GTranslate request and scraping to happen.

Maybe both errors are because the text is big, is this caused by google api or lingva? 
 
> You can also try in other instances to see if they also have that error.

same issue with https://lingva.pussthecat.org

Luca

**Comment by TheDavidDelta** [comment] 2022-05-04 19:10
Yes! The errors are caused by the big text.
This is because Lingva communicates with GTranslate by doing a standard GET request and scraping the responded webpage, and GET requests have character limit.

The thing is that Lingva should give an error in this case instead of printing some HTML code. This seems to be caused because of a bug in very specific GTranslate requests. I've just pushed a PR contemplating these edge cases, as well as setting a character limit (7500).
I think those are enough characters for most of the people. Otherwise, just split the translation. There's no other easy fix for this for the moment unfortunately, as it comes from the app architecture.

Regards, David.

**Closed** 2022-05-04 19:11 UTC
Labels: bug, question
